# Generated by Django 5.0.6 on 2024-06-07 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Author',
            new_name='Authors',
        ),
        migrations.RenameModel(
            old_name='Book',
            new_name='Books',
        ),
        migrations.RenameModel(
            old_name='BorrowingRecord',
            new_name='BorrowingRecords',
        ),
        migrations.RenameModel(
            old_name='Member',
            new_name='Members',
        ),
    ]
